#!/usr/bin/env bash
# Regenerate the project-root `eslint.config.bnb.mjs` overlay.
#
# When no active run exists, writes an empty stub that still exports an empty
# array, so a user who's already wired `import bnb from './eslint.config.bnb.mjs'`
# into their real config doesn't see breakage.
#
# When an active run exists, iterates `.bnb/<slug>/validation/eslint/*.json`
# and composes them into a single flat-config array export.
#
# Usage: regen-eslint-overlay.sh [project-root]
#
# Idempotent. Always overwrites eslint.config.bnb.mjs at project root. This
# single file is listed as a managed path in README / CLAUDE.md — users should
# not hand-edit it. forbidden_write_patterns guards it from fixer, but init
# and break own it.

set -euo pipefail

PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
PROJECT_ROOT="${1:-$(pwd)}"
OUT="$PROJECT_ROOT/eslint.config.bnb.mjs"

RUN_DIR=""
RUN_SLUG=""
if [ -f "$PROJECT_ROOT/.bnb/CURRENT_RUN" ]; then
  RUN_SLUG=$(tr -d '[:space:]' < "$PROJECT_ROOT/.bnb/CURRENT_RUN" | head -c 200)
  [ -n "$RUN_SLUG" ] && RUN_DIR="$PROJECT_ROOT/.bnb/$RUN_SLUG"
fi

ESLINT_DIR=""
[ -n "$RUN_DIR" ] && ESLINT_DIR="$RUN_DIR/validation/eslint"

CFG_LINES=""
if [ -n "$ESLINT_DIR" ] && [ -d "$ESLINT_DIR" ]; then
  while IFS= read -r f; do
    [ -f "$f" ] || continue
    rel="${f#$PROJECT_ROOT/}"
    CFG_LINES+="  // from $rel"$'\n'
    CFG_LINES+="  JSON.parse(readFileSync(new URL('./$rel', import.meta.url), 'utf8')),"$'\n'
  done < <(find "$ESLINT_DIR" -maxdepth 1 -type f -name '*.json' | LC_ALL=C sort)
fi

{
  echo "// eslint.config.bnb.mjs — generated by break-n-bake."
  echo "// Regenerated on every /break-n-bake:init and /break-n-bake:break."
  echo "// Do NOT hand-edit. Add rules by creating a new numbered file under"
  echo "// .bnb/<active-slug>/validation/eslint/."
  echo "//"
  echo "// Usage in your real eslint config:"
  echo "//   import bnb from './eslint.config.bnb.mjs';"
  echo "//   export default [ ...yourExistingConfigs, ...bnb ];"
  echo
  if [ -n "$CFG_LINES" ]; then
    echo "import { readFileSync } from 'node:fs';"
    echo
    echo "const bnb = ["
    printf '%s' "$CFG_LINES"
    echo "];"
    echo
    echo "export default bnb;"
  else
    echo "// No active run or no eslint overlays present. Empty export."
    echo "export default [];"
  fi
} > "$OUT"

if [ -n "$RUN_SLUG" ]; then
  count=0
  if [ -d "$ESLINT_DIR" ]; then
    count=$(find "$ESLINT_DIR" -maxdepth 1 -type f -name '*.json' | wc -l | tr -d ' ')
  fi
  echo "eslint-overlay: regenerated for run '$RUN_SLUG' ($count config(s)) → $OUT"
else
  echo "eslint-overlay: stub written (no active run) → $OUT"
fi
